{% set version = "0.5.3" %}

package:
  name: contextlib2
  version: {{ version }}

source:
  fn: contextlib2-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/contextlib2/contextlib2-{{ version }}.tar.gz
  sha256: 30e500f13921c73c96f49a6dd2adfbdd92bc3fae12183e91b06b2e4583486206

build:
  script: python setup.py install
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - contextlib2

about:
  home: http://contextlib2.readthedocs.org
  license: PSF License
  summary: 'Backports and enhancements for the contextlib module'

extra:
  recipe-maintainers:
    - dopplershift
